import { Container } from "inversify";
import DatabaseConnector from "./config/databaseConnector";
import RedisConnector from "./config/redisConnector";
import { TYPES } from "./types";
import { AuthController } from "./controllers/authController";
import { AdminController } from "./controllers/adminController";
import { ProController } from "./controllers/proController";
import { UserController } from "./controllers/userController";
import { ChatController } from "./controllers/chatController";
import { NotificationController } from "./controllers/notificationController";
import { RatingReviewController } from "./controllers/ratingReviewController";
import { TicketController } from "./controllers/ticketController";
import { UploadController } from "./controllers/uploadController";
import { AuthService } from "./services/AuthService";
import { IAuthService } from "./services/IAuthService";
import { AdminService } from "./services/AdminService";
import { IAdminService } from "./services/IAdminService";
import { ProService } from "./services/ProService";
import { IProService } from "./services/IProService";
import { UserService } from "./services/UserService";
import { IUserService } from "./services/IUserService";
import { ChatService } from "./services/ChatService";
import { IChatService } from "./services/IChatService";
import { NotificationService } from "./services/NotificationService";
import { INotificationService } from "./services/INotificationService";
import { RatingReviewService } from "./services/RatingReviewService";
import { IRatingReviewService } from "./services/IRatingReviewService";
import { ITicketService } from "./services/ITicketService";
import { TicketService } from "./services/ticketService";
import { UploadService } from "./services/UploadService";
import { IUploadService } from "./services/IUploadService";
import { IUserRepository } from "./repositories/IUserRepository";
import { IAdminRepository } from "./repositories/IAdminRepository";
import { IProRepository } from "./repositories/IProRepository";
import { ICategoryRepository } from "./repositories/ICategoryRepository";
import { IBookingRepository } from "./repositories/IBookingRepository";
import { IQuotaRepository } from "./repositories/IQuotaRepository";
import { IWalletRepository } from "./repositories/IWalletRepository";
import { IWithdrawalRequestRepository } from "./repositories/IWithdrawalRequestRepository";
import { IChatRepository } from "./repositories/IChatRepository";
import { INotificationRepository } from "./repositories/INotificationRepository";
import { IRatingReviewRepository } from "./repositories/IRatingReviewRepository";
import { ITransactionRepository } from "./repositories/ITransactionRepository";
import { ITicketRepository } from "./repositories/ITicketRepository";
import { MongoUserRepository } from "./repositories/UserRepository";
import { MongoAdminRepository } from "./repositories/AdminRepository";
import { MongoProRepository } from "./repositories/ProRepository";
import { MongoCategoryRepository } from "./repositories/CategoryRepository";
import { MongoBookingRepository } from "./repositories/BookingRepository";
import { MongoQuotaRepository } from "./repositories/QuotaRepository";
import { MongoWalletRepository } from "./repositories/WalletRepository";
import { MongoWithdrawalRequestRepository } from "./repositories/WithdrawalRequestRepository";
import { MongoChatRepository } from "./repositories/ChatRepository";
import { MongoNotificationRepository } from "./repositories/NotificationRepository";
import { MongoRatingReviewRepository } from "./repositories/ratingReviewRepository";
import { MongoTransactionRepository } from "./repositories/TransactionRepository";
import { MongoTicketRepository } from "./repositories/ticketRepository";
import { ChatGateway } from "./chatGateway";

const container = new Container();
container.bind<DatabaseConnector>(TYPES.DatabaseConnector).to(DatabaseConnector).inSingletonScope();
container.bind<RedisConnector>(TYPES.RedisConnector).to(RedisConnector).inSingletonScope();
container.bind<IUserRepository>(TYPES.IUserRepository).to(MongoUserRepository).inSingletonScope();
container.bind<IAdminRepository>(TYPES.IAdminRepository).to(MongoAdminRepository).inSingletonScope();
container.bind<IProRepository>(TYPES.IProRepository).to(MongoProRepository).inSingletonScope();
container.bind<ICategoryRepository>(TYPES.ICategoryRepository).to(MongoCategoryRepository).inSingletonScope();
container.bind<IBookingRepository>(TYPES.IBookingRepository).to(MongoBookingRepository).inSingletonScope();
container.bind<IQuotaRepository>(TYPES.IQuotaRepository).to(MongoQuotaRepository).inSingletonScope();
container.bind<IWalletRepository>(TYPES.IWalletRepository).to(MongoWalletRepository).inSingletonScope();
container.bind<IWithdrawalRequestRepository>(TYPES.IWithdrawalRequestRepository).to(MongoWithdrawalRequestRepository).inSingletonScope();
container.bind<IChatRepository>(TYPES.IChatRepository).to(MongoChatRepository).inSingletonScope();
container.bind<INotificationRepository>(TYPES.INotificationRepository).to(MongoNotificationRepository).inSingletonScope();
container.bind<IRatingReviewRepository>(TYPES.IRatingReviewRepository).to(MongoRatingReviewRepository).inSingletonScope();
container.bind<ITransactionRepository>(TYPES.ITransactionRepository).to(MongoTransactionRepository).inSingletonScope();
container.bind<ITicketRepository>(TYPES.ITicketRepository).to(MongoTicketRepository).inSingletonScope();
container.bind<IAuthService>(TYPES.IAuthService).to(AuthService).inSingletonScope();
container.bind<IAdminService>(TYPES.IAdminService).to(AdminService).inSingletonScope();
container.bind<IProService>(TYPES.IProService).to(ProService).inSingletonScope();
container.bind<IUserService>(TYPES.IUserService).to(UserService).inSingletonScope();
container.bind<IChatService>(TYPES.IChatService).to(ChatService).inSingletonScope();
container.bind<INotificationService>(TYPES.INotificationService).to(NotificationService).inSingletonScope();
container.bind<IRatingReviewService>(TYPES.IRatingReviewService).to(RatingReviewService).inSingletonScope();
container.bind<ITicketService>(TYPES.ITicketService).to(TicketService).inSingletonScope();
container.bind<IUploadService>(TYPES.IUploadService).to(UploadService).inSingletonScope();
container.bind<AuthController>(TYPES.AuthController).to(AuthController).inSingletonScope();
container.bind<AdminController>(TYPES.AdminController).to(AdminController).inSingletonScope();
container.bind<ProController>(TYPES.ProController).to(ProController).inSingletonScope();
container.bind<UserController>(TYPES.UserController).to(UserController).inSingletonScope();
container.bind<ChatController>(TYPES.ChatController).to(ChatController).inSingletonScope();
container.bind<NotificationController>(TYPES.NotificationController).to(NotificationController).inSingletonScope();
container.bind<RatingReviewController>(TYPES.RatingReviewController).to(RatingReviewController).inSingletonScope();
container.bind<TicketController>(TYPES.TicketController).to(TicketController).inSingletonScope();
container.bind<UploadController>(TYPES.UploadController).to(UploadController).inSingletonScope();
container.bind<ChatGateway>(TYPES.ChatGateway).to(ChatGateway).inSingletonScope();

export default container;
